name: learn-guthub-workflow
run-name: ${{github.actor}} is learning github-actions
# on: [push]
jobs:
    first-run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: actions/setup-node@v6
              with: 
                node-version: '24'
            - run: npm install -g bats
            - run: bats -v
    second-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello from second job"