name: 02-workflow
run-name: "checking types on trigger"
on: 
#  push:
#     branches:
#         - second
    workflow_dispatch:
jobs:
    on-types:
        runs-on: ubuntu-latest
        steps:
            - run: echo "on push to second branch, this ran"