name: run-on-label
run-name: on-label-creation
on: 
    label:
            types:
                - created
    push:
        branches:   
            - main
jobs:
    on-label:
      runs-on: ubuntu-latest
      steps:
        - run: echo "on label creation, this ran"