name: outputs
on:
    workflow_dispatch:

    workflow_call:
        outputs:
            final_output:
                value: ${{ jobs.producer.outputs.output1 }}
jobs:
    producer:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{  steps.creator.outputs.name }} 
        steps:
            - name: generator and verify
              id: creator
              run: |
               foo="Jagadish"
               echo "name=$foo" >> "$GITHUB_OUTPUT"

               echo "NAME=$foo" >> "$GITHUB_ENV"
            - name: inspect output and variable
              run: |
                echo "FOO is : $NAME"
                echo "FOO is (through outputs): ${{ steps.creator.outputs.name }}"
    consumer:
        runs-on: ubuntu-latest
        needs: producer 
        steps:
            - name: consume output of previous job
              run: |
                    echo "FOO is: ${{ needs.producer.outputs.output1 }}"
                    echo "FOO is: $NAME"
            


