name: permissions
on:
    workflow_dispatch
jobs:
    read:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            issues: write
            pull_requests: read
        continue-on-error: true
        steps:
            - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
            
            - name: List the first 5 open prs
              run: gh pr list --limit 5
              env: 
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}      
            - name: attempt to add a Label
              run:  gh pr edit 1 --add-label "documentation"

            - name: confirm the failure
              if: failure()
              run: echo "❌  Write operation was blocked as expected – token is read-only."

    
          
