name: matrix-mit-include
on:
    workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
    setup:
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            max-parallel: 2
            fail-fast: true
            matrix:
                version: [ 10 , 12 , 13]
                os: [ ubuntu , redhat , windows]
                experimental: [false]
                exclude: 
                    - version: 12
                      os: windows
                include:
                    - version: 14
                      experimental: true
        timeout-minutes: 5

        steps:
            - name: print the worflow os
              run: echo "${{ matrix.os }}"
            - name: print worflow version
              run: echo "${{ matrix.version }}"

    sleep-job:
        runs-on: ubuntu-24.04
        steps:
            - name: Sleep (to give time to be cancelled)
              run: sleep 1000
              timeout-minutes: 2