name: reusable-caller
on: 
    workflow_dispatch:
jobs:
    call-resubale-workflow:
        uses: ./.github/workflows/17-workflow.yml
        name: calling the reusable workflow
        with:
            environment: prod
            foo: Valluri
        secrets: inherit
    
    from-show:
        uses: jagadishvvsr/GitHubActions/.github/workflows/17-workflow.yml@b71ebded0eb8f0ccc91da77ee89c8770502b728c
        name: from sha
        with:
            environment: stage
            foo: Sita Ram
        secrets:
            EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}